# Generated by Django 2.2.4 on 2019-08-09 19:05

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debate_author', models.CharField(max_length=200)),
                ('debate_text', models.TextField()),
                ('debate_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('debate_approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='debate',
            name='agree',
            field=models.ManyToManyField(blank=True, related_name='agree_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debate',
            name='disagree',
            field=models.ManyToManyField(blank=True, related_name='disagree_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debate',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='debate_comment',
            name='debate_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_comments', to='debate.Debate'),
        ),
    ]
